/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : bigint,
  'action' : string,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'details' : string,
}
export type ExternalBlob = Uint8Array;
export interface Location {
  'lat' : number,
  'lng' : number,
  'displayName' : string,
}
export interface NGOProfileInput {
  'name' : string,
  'description' : string,
  'website' : string,
  'contactEmail' : string,
}
export interface NGOProfilePublic {
  'id' : UserId,
  'status' : NGOStatus,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'website' : string,
  'updatedAt' : Timestamp,
  'contactEmail' : string,
}
export type NGOStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type NotificationId = bigint;
export interface NotificationPublic {
  'id' : NotificationId,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
  'message' : string,
}
export type NotificationType = { 'completion' : null } |
  { 'assignment' : null } |
  { 'reminder' : null } |
  { 'rejection' : null } |
  { 'acceptance' : null };
export interface PlatformStats {
  'totalVolunteers' : bigint,
  'totalTasks' : bigint,
  'completionRate' : number,
  'completedTasks' : bigint,
  'totalNGOs' : bigint,
  'pendingNGOs' : bigint,
  'verifiedTasks' : bigint,
}
export type TaskId = bigint;
export interface TaskInput {
  'title' : string,
  'description' : string,
  'deadline' : Timestamp,
  'priority' : TaskPriority,
  'requiredSkills' : Array<string>,
  'location' : [] | [Location],
}
export type TaskPriority = { 'normal' : null } |
  { 'urgent' : null };
export interface TaskPublic {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'proofUrls' : Array<ExternalBlob>,
  'createdByNGO' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'deadline' : Timestamp,
  'updatedAt' : Timestamp,
  'priority' : TaskPriority,
  'assignedVolunteer' : [] | [UserId],
  'requiredSkills' : Array<string>,
  'location' : [] | [Location],
}
export type TaskStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface TaskWithScore { 'task' : TaskPublic, 'matchScore' : number }
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserRole__1 = { 'ngo' : null } |
  { 'superAdmin' : null } |
  { 'volunteer' : null };
export interface VolunteerProfileInput {
  'bio' : string,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'availability' : string,
  'skills' : Array<string>,
  'location' : [] | [Location],
}
export interface VolunteerProfilePublic {
  'id' : UserId,
  'bio' : string,
  'ratingCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'profilePhoto' : [] | [ExternalBlob],
  'isActive' : boolean,
  'availability' : string,
  'updatedAt' : Timestamp,
  'rating' : number,
  'skills' : Array<string>,
  'location' : [] | [Location],
  'totalTasksCompleted' : bigint,
}
export interface VolunteerWithScore {
  'matchScore' : number,
  'profile' : VolunteerProfilePublic,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptTask' : ActorMethod<[TaskId], boolean>,
  'approveNGO' : ActorMethod<[UserId, boolean], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[UserId, UserRole__1], undefined>,
  'assignVolunteer' : ActorMethod<[TaskId, UserId], boolean>,
  'createTask' : ActorMethod<[TaskInput], TaskId>,
  'deactivateNGO' : ActorMethod<[UserId], undefined>,
  'deactivateVolunteer' : ActorMethod<[UserId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], boolean>,
  'filterVolunteersBySkills' : ActorMethod<
    [Array<string>],
    Array<VolunteerProfilePublic>
  >,
  'getActivityLog' : ActorMethod<[], Array<ActivityLog>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchScore' : ActorMethod<[UserId, TaskId], number>,
  'getMyNGOProfile' : ActorMethod<[], [] | [NGOProfilePublic]>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationPublic>>,
  'getMyRecommendedTasks' : ActorMethod<[bigint], Array<TaskWithScore>>,
  'getMyVolunteerProfile' : ActorMethod<[], [] | [VolunteerProfilePublic]>,
  'getNGOProfile' : ActorMethod<[UserId], [] | [NGOProfilePublic]>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getRecommendedTasks' : ActorMethod<[UserId, bigint], Array<TaskWithScore>>,
  'getTask' : ActorMethod<[TaskId], [] | [TaskPublic]>,
  'getTopVolunteers' : ActorMethod<[TaskId, bigint], Array<VolunteerWithScore>>,
  'getVolunteerProfile' : ActorMethod<[UserId], [] | [VolunteerProfilePublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllTasks' : ActorMethod<[], Array<TaskPublic>>,
  'listMyNGOTasks' : ActorMethod<[], Array<TaskPublic>>,
  'listMyVolunteerTasks' : ActorMethod<[], Array<TaskPublic>>,
  'listNGOs' : ActorMethod<[], Array<NGOProfilePublic>>,
  'listPendingNGOs' : ActorMethod<[], Array<NGOProfilePublic>>,
  'listVolunteers' : ActorMethod<[], Array<VolunteerProfilePublic>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'markTaskCompleted' : ActorMethod<[TaskId, Array<ExternalBlob>], boolean>,
  'registerNGO' : ActorMethod<[NGOProfileInput], undefined>,
  'rejectTask' : ActorMethod<[TaskId], boolean>,
  'saveMyVolunteerProfile' : ActorMethod<[VolunteerProfileInput], undefined>,
  'updateMyNGOProfile' : ActorMethod<[NGOProfileInput], undefined>,
  'updateTask' : ActorMethod<[TaskId, TaskInput], boolean>,
  'verifyTask' : ActorMethod<[TaskId, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];