/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TaskId = IDL.Nat;
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'ngo' : IDL.Null,
  'superAdmin' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const TaskPriority = IDL.Variant({
  'normal' : IDL.Null,
  'urgent' : IDL.Null,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'displayName' : IDL.Text,
});
export const TaskInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'priority' : TaskPriority,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'location' : IDL.Opt(Location),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const VolunteerProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'ratingCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'isActive' : IDL.Bool,
  'availability' : IDL.Text,
  'updatedAt' : Timestamp,
  'rating' : IDL.Float64,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Opt(Location),
  'totalTasksCompleted' : IDL.Nat,
});
export const ActivityLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
});
export const NGOStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const NGOProfilePublic = IDL.Record({
  'id' : UserId,
  'status' : NGOStatus,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'website' : IDL.Text,
  'updatedAt' : Timestamp,
  'contactEmail' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'completion' : IDL.Null,
  'assignment' : IDL.Null,
  'reminder' : IDL.Null,
  'rejection' : IDL.Null,
  'acceptance' : IDL.Null,
});
export const NotificationPublic = IDL.Record({
  'id' : NotificationId,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const TaskPublic = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'proofUrls' : IDL.Vec(ExternalBlob),
  'createdByNGO' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'updatedAt' : Timestamp,
  'priority' : TaskPriority,
  'assignedVolunteer' : IDL.Opt(UserId),
  'requiredSkills' : IDL.Vec(IDL.Text),
  'location' : IDL.Opt(Location),
});
export const TaskWithScore = IDL.Record({
  'task' : TaskPublic,
  'matchScore' : IDL.Float64,
});
export const PlatformStats = IDL.Record({
  'totalVolunteers' : IDL.Nat,
  'totalTasks' : IDL.Nat,
  'completionRate' : IDL.Float64,
  'completedTasks' : IDL.Nat,
  'totalNGOs' : IDL.Nat,
  'pendingNGOs' : IDL.Nat,
  'verifiedTasks' : IDL.Nat,
});
export const VolunteerWithScore = IDL.Record({
  'matchScore' : IDL.Float64,
  'profile' : VolunteerProfilePublic,
});
export const NGOProfileInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const VolunteerProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'availability' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Opt(Location),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'approveNGO' : IDL.Func([UserId, IDL.Bool], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([UserId, UserRole__1], [], []),
  'assignVolunteer' : IDL.Func([TaskId, UserId], [IDL.Bool], []),
  'createTask' : IDL.Func([TaskInput], [TaskId], []),
  'deactivateNGO' : IDL.Func([UserId], [], []),
  'deactivateVolunteer' : IDL.Func([UserId], [], []),
  'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'filterVolunteersBySkills' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(VolunteerProfilePublic)],
      ['query'],
    ),
  'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchScore' : IDL.Func([UserId, TaskId], [IDL.Float64], ['query']),
  'getMyNGOProfile' : IDL.Func([], [IDL.Opt(NGOProfilePublic)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], ['query']),
  'getMyRecommendedTasks' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TaskWithScore)],
      ['query'],
    ),
  'getMyVolunteerProfile' : IDL.Func(
      [],
      [IDL.Opt(VolunteerProfilePublic)],
      ['query'],
    ),
  'getNGOProfile' : IDL.Func([UserId], [IDL.Opt(NGOProfilePublic)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getRecommendedTasks' : IDL.Func(
      [UserId, IDL.Nat],
      [IDL.Vec(TaskWithScore)],
      ['query'],
    ),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(TaskPublic)], ['query']),
  'getTopVolunteers' : IDL.Func(
      [TaskId, IDL.Nat],
      [IDL.Vec(VolunteerWithScore)],
      ['query'],
    ),
  'getVolunteerProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(VolunteerProfilePublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllTasks' : IDL.Func([], [IDL.Vec(TaskPublic)], ['query']),
  'listMyNGOTasks' : IDL.Func([], [IDL.Vec(TaskPublic)], ['query']),
  'listMyVolunteerTasks' : IDL.Func([], [IDL.Vec(TaskPublic)], ['query']),
  'listNGOs' : IDL.Func([], [IDL.Vec(NGOProfilePublic)], ['query']),
  'listPendingNGOs' : IDL.Func([], [IDL.Vec(NGOProfilePublic)], ['query']),
  'listVolunteers' : IDL.Func([], [IDL.Vec(VolunteerProfilePublic)], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'markTaskCompleted' : IDL.Func(
      [TaskId, IDL.Vec(ExternalBlob)],
      [IDL.Bool],
      [],
    ),
  'registerNGO' : IDL.Func([NGOProfileInput], [], []),
  'rejectTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'saveMyVolunteerProfile' : IDL.Func([VolunteerProfileInput], [], []),
  'updateMyNGOProfile' : IDL.Func([NGOProfileInput], [], []),
  'updateTask' : IDL.Func([TaskId, TaskInput], [IDL.Bool], []),
  'verifyTask' : IDL.Func([TaskId, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TaskId = IDL.Nat;
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole__1 = IDL.Variant({
    'ngo' : IDL.Null,
    'superAdmin' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const TaskPriority = IDL.Variant({
    'normal' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'displayName' : IDL.Text,
  });
  const TaskInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'priority' : TaskPriority,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'location' : IDL.Opt(Location),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const VolunteerProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'ratingCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'isActive' : IDL.Bool,
    'availability' : IDL.Text,
    'updatedAt' : Timestamp,
    'rating' : IDL.Float64,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Opt(Location),
    'totalTasksCompleted' : IDL.Nat,
  });
  const ActivityLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'userId' : UserId,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
  });
  const NGOStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const NGOProfilePublic = IDL.Record({
    'id' : UserId,
    'status' : NGOStatus,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'website' : IDL.Text,
    'updatedAt' : Timestamp,
    'contactEmail' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'completion' : IDL.Null,
    'assignment' : IDL.Null,
    'reminder' : IDL.Null,
    'rejection' : IDL.Null,
    'acceptance' : IDL.Null,
  });
  const NotificationPublic = IDL.Record({
    'id' : NotificationId,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const TaskPublic = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'proofUrls' : IDL.Vec(ExternalBlob),
    'createdByNGO' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'updatedAt' : Timestamp,
    'priority' : TaskPriority,
    'assignedVolunteer' : IDL.Opt(UserId),
    'requiredSkills' : IDL.Vec(IDL.Text),
    'location' : IDL.Opt(Location),
  });
  const TaskWithScore = IDL.Record({
    'task' : TaskPublic,
    'matchScore' : IDL.Float64,
  });
  const PlatformStats = IDL.Record({
    'totalVolunteers' : IDL.Nat,
    'totalTasks' : IDL.Nat,
    'completionRate' : IDL.Float64,
    'completedTasks' : IDL.Nat,
    'totalNGOs' : IDL.Nat,
    'pendingNGOs' : IDL.Nat,
    'verifiedTasks' : IDL.Nat,
  });
  const VolunteerWithScore = IDL.Record({
    'matchScore' : IDL.Float64,
    'profile' : VolunteerProfilePublic,
  });
  const NGOProfileInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const VolunteerProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'availability' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Opt(Location),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'approveNGO' : IDL.Func([UserId, IDL.Bool], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([UserId, UserRole__1], [], []),
    'assignVolunteer' : IDL.Func([TaskId, UserId], [IDL.Bool], []),
    'createTask' : IDL.Func([TaskInput], [TaskId], []),
    'deactivateNGO' : IDL.Func([UserId], [], []),
    'deactivateVolunteer' : IDL.Func([UserId], [], []),
    'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'filterVolunteersBySkills' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(VolunteerProfilePublic)],
        ['query'],
      ),
    'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchScore' : IDL.Func([UserId, TaskId], [IDL.Float64], ['query']),
    'getMyNGOProfile' : IDL.Func([], [IDL.Opt(NGOProfilePublic)], ['query']),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationPublic)],
        ['query'],
      ),
    'getMyRecommendedTasks' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TaskWithScore)],
        ['query'],
      ),
    'getMyVolunteerProfile' : IDL.Func(
        [],
        [IDL.Opt(VolunteerProfilePublic)],
        ['query'],
      ),
    'getNGOProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(NGOProfilePublic)],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getRecommendedTasks' : IDL.Func(
        [UserId, IDL.Nat],
        [IDL.Vec(TaskWithScore)],
        ['query'],
      ),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(TaskPublic)], ['query']),
    'getTopVolunteers' : IDL.Func(
        [TaskId, IDL.Nat],
        [IDL.Vec(VolunteerWithScore)],
        ['query'],
      ),
    'getVolunteerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(VolunteerProfilePublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllTasks' : IDL.Func([], [IDL.Vec(TaskPublic)], ['query']),
    'listMyNGOTasks' : IDL.Func([], [IDL.Vec(TaskPublic)], ['query']),
    'listMyVolunteerTasks' : IDL.Func([], [IDL.Vec(TaskPublic)], ['query']),
    'listNGOs' : IDL.Func([], [IDL.Vec(NGOProfilePublic)], ['query']),
    'listPendingNGOs' : IDL.Func([], [IDL.Vec(NGOProfilePublic)], ['query']),
    'listVolunteers' : IDL.Func(
        [],
        [IDL.Vec(VolunteerProfilePublic)],
        ['query'],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'markTaskCompleted' : IDL.Func(
        [TaskId, IDL.Vec(ExternalBlob)],
        [IDL.Bool],
        [],
      ),
    'registerNGO' : IDL.Func([NGOProfileInput], [], []),
    'rejectTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'saveMyVolunteerProfile' : IDL.Func([VolunteerProfileInput], [], []),
    'updateMyNGOProfile' : IDL.Func([NGOProfileInput], [], []),
    'updateTask' : IDL.Func([TaskId, TaskInput], [IDL.Bool], []),
    'verifyTask' : IDL.Func([TaskId, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };