/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
    displayName: string;
}
export type Timestamp = bigint;
export interface VolunteerProfilePublic {
    id: UserId;
    bio: string;
    ratingCount: bigint;
    name: string;
    createdAt: Timestamp;
    profilePhoto?: ExternalBlob;
    isActive: boolean;
    availability: string;
    updatedAt: Timestamp;
    rating: number;
    skills: Array<string>;
    location?: Location;
    totalTasksCompleted: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface NGOProfilePublic {
    id: UserId;
    status: NGOStatus;
    name: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    website: string;
    updatedAt: Timestamp;
    contactEmail: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface NGOProfileInput {
    name: string;
    description: string;
    website: string;
    contactEmail: string;
}
export interface ActivityLog {
    id: bigint;
    action: string;
    userId: UserId;
    timestamp: Timestamp;
    details: string;
}
export interface VolunteerWithScore {
    matchScore: number;
    profile: VolunteerProfilePublic;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export interface TaskInput {
    title: string;
    description: string;
    deadline: Timestamp;
    priority: TaskPriority;
    requiredSkills: Array<string>;
    location?: Location;
}
export interface VolunteerProfileInput {
    bio: string;
    name: string;
    profilePhoto?: ExternalBlob;
    availability: string;
    skills: Array<string>;
    location?: Location;
}
export interface TaskPublic {
    id: TaskId;
    status: TaskStatus;
    title: string;
    proofUrls: Array<ExternalBlob>;
    createdByNGO: UserId;
    createdAt: Timestamp;
    description: string;
    deadline: Timestamp;
    updatedAt: Timestamp;
    priority: TaskPriority;
    assignedVolunteer?: UserId;
    requiredSkills: Array<string>;
    location?: Location;
}
export type TaskId = bigint;
export interface TaskWithScore {
    task: TaskPublic;
    matchScore: number;
}
export type NotificationId = bigint;
export interface PlatformStats {
    totalVolunteers: bigint;
    totalTasks: bigint;
    completionRate: number;
    completedTasks: bigint;
    totalNGOs: bigint;
    pendingNGOs: bigint;
    verifiedTasks: bigint;
}
export interface NotificationPublic {
    id: NotificationId;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
    message: string;
}
export enum NGOStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum NotificationType {
    completion = "completion",
    assignment = "assignment",
    reminder = "reminder",
    rejection = "rejection",
    acceptance = "acceptance"
}
export enum TaskPriority {
    normal = "normal",
    urgent = "urgent"
}
export enum TaskStatus {
    verified = "verified",
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserRole__1 {
    ngo = "ngo",
    superAdmin = "superAdmin",
    volunteer = "volunteer"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptTask(taskId: TaskId): Promise<boolean>;
    approveNGO(userId: UserId, approve: boolean): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(userId: UserId, role: UserRole__1): Promise<void>;
    assignVolunteer(taskId: TaskId, volunteerId: UserId): Promise<boolean>;
    createTask(input: TaskInput): Promise<TaskId>;
    deactivateNGO(userId: UserId): Promise<void>;
    deactivateVolunteer(userId: UserId): Promise<void>;
    deleteTask(taskId: TaskId): Promise<boolean>;
    filterVolunteersBySkills(skills: Array<string>): Promise<Array<VolunteerProfilePublic>>;
    getActivityLog(): Promise<Array<ActivityLog>>;
    getCallerUserRole(): Promise<UserRole>;
    getMatchScore(volunteerId: UserId, taskId: TaskId): Promise<number>;
    getMyNGOProfile(): Promise<NGOProfilePublic | null>;
    getMyNotifications(): Promise<Array<NotificationPublic>>;
    getMyRecommendedTasks(limit: bigint): Promise<Array<TaskWithScore>>;
    getMyVolunteerProfile(): Promise<VolunteerProfilePublic | null>;
    getNGOProfile(userId: UserId): Promise<NGOProfilePublic | null>;
    getPlatformStats(): Promise<PlatformStats>;
    getRecommendedTasks(volunteerId: UserId, limit: bigint): Promise<Array<TaskWithScore>>;
    getTask(taskId: TaskId): Promise<TaskPublic | null>;
    getTopVolunteers(taskId: TaskId, limit: bigint): Promise<Array<VolunteerWithScore>>;
    getVolunteerProfile(userId: UserId): Promise<VolunteerProfilePublic | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllTasks(): Promise<Array<TaskPublic>>;
    listMyNGOTasks(): Promise<Array<TaskPublic>>;
    listMyVolunteerTasks(): Promise<Array<TaskPublic>>;
    listNGOs(): Promise<Array<NGOProfilePublic>>;
    listPendingNGOs(): Promise<Array<NGOProfilePublic>>;
    listVolunteers(): Promise<Array<VolunteerProfilePublic>>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(notificationId: NotificationId): Promise<boolean>;
    markTaskCompleted(taskId: TaskId, proofs: Array<ExternalBlob>): Promise<boolean>;
    registerNGO(input: NGOProfileInput): Promise<void>;
    rejectTask(taskId: TaskId): Promise<boolean>;
    saveMyVolunteerProfile(input: VolunteerProfileInput): Promise<void>;
    updateMyNGOProfile(input: NGOProfileInput): Promise<void>;
    updateTask(taskId: TaskId, input: TaskInput): Promise<boolean>;
    verifyTask(taskId: TaskId, approved: boolean): Promise<boolean>;
}
import type { ExternalBlob as _ExternalBlob, Location as _Location, NGOProfilePublic as _NGOProfilePublic, NGOStatus as _NGOStatus, NotificationId as _NotificationId, NotificationPublic as _NotificationPublic, NotificationType as _NotificationType, TaskId as _TaskId, TaskInput as _TaskInput, TaskPriority as _TaskPriority, TaskPublic as _TaskPublic, TaskStatus as _TaskStatus, TaskWithScore as _TaskWithScore, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, UserRole__1 as _UserRole__1, VolunteerProfileInput as _VolunteerProfileInput, VolunteerProfilePublic as _VolunteerProfilePublic, VolunteerWithScore as _VolunteerWithScore, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTask(arg0);
            return result;
        }
    }
    async approveNGO(arg0: UserId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveNGO(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveNGO(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: UserId, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserRole__1_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserRole__1_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignVolunteer(arg0: TaskId, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignVolunteer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignVolunteer(arg0, arg1);
            return result;
        }
    }
    async createTask(arg0: TaskInput): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_TaskInput_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_TaskInput_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deactivateNGO(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateNGO(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateNGO(arg0);
            return result;
        }
    }
    async deactivateVolunteer(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateVolunteer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateVolunteer(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async filterVolunteersBySkills(arg0: Array<string>): Promise<Array<VolunteerProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterVolunteersBySkills(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterVolunteersBySkills(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLog(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchScore(arg0: UserId, arg1: TaskId): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchScore(arg0, arg1);
            return result;
        }
    }
    async getMyNGOProfile(): Promise<NGOProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNGOProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNGOProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<NotificationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRecommendedTasks(arg0: bigint): Promise<Array<TaskWithScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRecommendedTasks(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRecommendedTasks(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVolunteerProfile(): Promise<VolunteerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVolunteerProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVolunteerProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNGOProfile(arg0: UserId): Promise<NGOProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNGOProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNGOProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getRecommendedTasks(arg0: UserId, arg1: bigint): Promise<Array<TaskWithScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedTasks(arg0, arg1);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedTasks(arg0, arg1);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: TaskId): Promise<TaskPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopVolunteers(arg0: TaskId, arg1: bigint): Promise<Array<VolunteerWithScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopVolunteers(arg0, arg1);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopVolunteers(arg0, arg1);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteerProfile(arg0: UserId): Promise<VolunteerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteerProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteerProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllTasks(): Promise<Array<TaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllTasks();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllTasks();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyNGOTasks(): Promise<Array<TaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyNGOTasks();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyNGOTasks();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyVolunteerTasks(): Promise<Array<TaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyVolunteerTasks();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyVolunteerTasks();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNGOs(): Promise<Array<NGOProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNGOs();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNGOs();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingNGOs(): Promise<Array<NGOProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingNGOs();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingNGOs();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVolunteers(): Promise<Array<VolunteerProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVolunteers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVolunteers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async markTaskCompleted(arg0: TaskId, arg1: Array<ExternalBlob>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markTaskCompleted(arg0, await to_candid_vec_n52(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTaskCompleted(arg0, await to_candid_vec_n52(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async registerNGO(arg0: NGOProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerNGO(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerNGO(arg0);
            return result;
        }
    }
    async rejectTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTask(arg0);
            return result;
        }
    }
    async saveMyVolunteerProfile(arg0: VolunteerProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMyVolunteerProfile(await to_candid_VolunteerProfileInput_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMyVolunteerProfile(await to_candid_VolunteerProfileInput_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMyNGOProfile(arg0: NGOProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyNGOProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyNGOProfile(arg0);
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: TaskInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_TaskInput_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_TaskInput_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyTask(arg0: TaskId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyTask(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_NGOProfilePublic_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NGOProfilePublic): NGOProfilePublic {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_NGOStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NGOStatus): NGOStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPublic_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPublic): NotificationPublic {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_TaskPublic_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPublic): Promise<TaskPublic> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_TaskWithScore_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskWithScore): Promise<TaskWithScore> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_VolunteerProfilePublic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VolunteerProfilePublic): Promise<VolunteerProfilePublic> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_VolunteerWithScore_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VolunteerWithScore): Promise<VolunteerWithScore> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NGOProfilePublic]): NGOProfilePublic | null {
    return value.length === 0 ? null : from_candid_NGOProfilePublic_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VolunteerProfilePublic]): Promise<VolunteerProfilePublic | null> {
    return value.length === 0 ? null : await from_candid_VolunteerProfilePublic_n17(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskPublic]): Promise<TaskPublic | null> {
    return value.length === 0 ? null : await from_candid_TaskPublic_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    ratingCount: bigint;
    name: string;
    createdAt: _Timestamp;
    profilePhoto: [] | [_ExternalBlob];
    isActive: boolean;
    availability: string;
    updatedAt: _Timestamp;
    rating: number;
    skills: Array<string>;
    location: [] | [_Location];
    totalTasksCompleted: bigint;
}): Promise<{
    id: UserId;
    bio: string;
    ratingCount: bigint;
    name: string;
    createdAt: Timestamp;
    profilePhoto?: ExternalBlob;
    isActive: boolean;
    availability: string;
    updatedAt: Timestamp;
    rating: number;
    skills: Array<string>;
    location?: Location;
    totalTasksCompleted: bigint;
}> {
    return {
        id: value.id,
        bio: value.bio,
        ratingCount: value.ratingCount,
        name: value.name,
        createdAt: value.createdAt,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.profilePhoto)),
        isActive: value.isActive,
        availability: value.availability,
        updatedAt: value.updatedAt,
        rating: value.rating,
        skills: value.skills,
        location: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.location)),
        totalTasksCompleted: value.totalTasksCompleted
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _NGOStatus;
    name: string;
    createdAt: _Timestamp;
    description: string;
    isActive: boolean;
    website: string;
    updatedAt: _Timestamp;
    contactEmail: string;
}): {
    id: UserId;
    status: NGOStatus;
    name: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    website: string;
    updatedAt: Timestamp;
    contactEmail: string;
} {
    return {
        id: value.id,
        status: from_candid_NGOStatus_n27(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        website: value.website,
        updatedAt: value.updatedAt,
        contactEmail: value.contactEmail
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    userId: _UserId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    read: boolean;
    message: string;
}): {
    id: NotificationId;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
    message: string;
} {
    return {
        id: value.id,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n32(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        read: value.read,
        message: value.message
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    task: _TaskPublic;
    matchScore: number;
}): Promise<{
    task: TaskPublic;
    matchScore: number;
}> {
    return {
        task: await from_candid_TaskPublic_n37(_uploadFile, _downloadFile, value.task),
        matchScore: value.matchScore
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    proofUrls: Array<_ExternalBlob>;
    createdByNGO: _UserId;
    createdAt: _Timestamp;
    description: string;
    deadline: _Timestamp;
    updatedAt: _Timestamp;
    priority: _TaskPriority;
    assignedVolunteer: [] | [_UserId];
    requiredSkills: Array<string>;
    location: [] | [_Location];
}): Promise<{
    id: TaskId;
    status: TaskStatus;
    title: string;
    proofUrls: Array<ExternalBlob>;
    createdByNGO: UserId;
    createdAt: Timestamp;
    description: string;
    deadline: Timestamp;
    updatedAt: Timestamp;
    priority: TaskPriority;
    assignedVolunteer?: UserId;
    requiredSkills: Array<string>;
    location?: Location;
}> {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n39(_uploadFile, _downloadFile, value.status),
        title: value.title,
        proofUrls: await from_candid_vec_n41(_uploadFile, _downloadFile, value.proofUrls),
        createdByNGO: value.createdByNGO,
        createdAt: value.createdAt,
        description: value.description,
        deadline: value.deadline,
        updatedAt: value.updatedAt,
        priority: from_candid_TaskPriority_n42(_uploadFile, _downloadFile, value.priority),
        assignedVolunteer: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.assignedVolunteer)),
        requiredSkills: value.requiredSkills,
        location: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.location))
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchScore: number;
    profile: _VolunteerProfilePublic;
}): Promise<{
    matchScore: number;
    profile: VolunteerProfilePublic;
}> {
    return {
        matchScore: value.matchScore,
        profile: await from_candid_VolunteerProfilePublic_n17(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): NGOStatus {
    return "pending" in value ? NGOStatus.pending : "approved" in value ? NGOStatus.approved : "rejected" in value ? NGOStatus.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completion: null;
} | {
    assignment: null;
} | {
    reminder: null;
} | {
    rejection: null;
} | {
    acceptance: null;
}): NotificationType {
    return "completion" in value ? NotificationType.completion : "assignment" in value ? NotificationType.assignment : "reminder" in value ? NotificationType.reminder : "rejection" in value ? NotificationType.rejection : "acceptance" in value ? NotificationType.acceptance : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): TaskStatus {
    return "verified" in value ? TaskStatus.verified : "pending" in value ? TaskStatus.pending : "completed" in value ? TaskStatus.completed : "rejected" in value ? TaskStatus.rejected : "accepted" in value ? TaskStatus.accepted : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    urgent: null;
}): TaskPriority {
    return "normal" in value ? TaskPriority.normal : "urgent" in value ? TaskPriority.urgent : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VolunteerProfilePublic>): Promise<Array<VolunteerProfilePublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VolunteerProfilePublic_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationPublic>): Array<NotificationPublic> {
    return value.map((x)=>from_candid_NotificationPublic_n30(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskWithScore>): Promise<Array<TaskWithScore>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TaskWithScore_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VolunteerWithScore>): Promise<Array<VolunteerWithScore>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VolunteerWithScore_n48(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskPublic>): Promise<Array<TaskPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TaskPublic_n37(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NGOProfilePublic>): Array<NGOProfilePublic> {
    return value.map((x)=>from_candid_NGOProfilePublic_n25(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TaskInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskInput): _TaskInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_VolunteerProfileInput_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VolunteerProfileInput): Promise<_VolunteerProfileInput> {
    return await to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    deadline: Timestamp;
    priority: TaskPriority;
    requiredSkills: Array<string>;
    location?: Location;
}): {
    title: string;
    description: string;
    deadline: _Timestamp;
    priority: _TaskPriority;
    requiredSkills: Array<string>;
    location: [] | [_Location];
} {
    return {
        title: value.title,
        description: value.description,
        deadline: value.deadline,
        priority: to_candid_TaskPriority_n14(_uploadFile, _downloadFile, value.priority),
        requiredSkills: value.requiredSkills,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    name: string;
    profilePhoto?: ExternalBlob;
    availability: string;
    skills: Array<string>;
    location?: Location;
}): Promise<{
    bio: string;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    availability: string;
    skills: Array<string>;
    location: [] | [_Location];
}> {
    return {
        bio: value.bio,
        name: value.name,
        profilePhoto: value.profilePhoto ? candid_some(await to_candid_ExternalBlob_n53(_uploadFile, _downloadFile, value.profilePhoto)) : candid_none(),
        availability: value.availability,
        skills: value.skills,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    ngo: null;
} | {
    superAdmin: null;
} | {
    volunteer: null;
} {
    return value == UserRole__1.ngo ? {
        ngo: null
    } : value == UserRole__1.superAdmin ? {
        superAdmin: null
    } : value == UserRole__1.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    normal: null;
} | {
    urgent: null;
} {
    return value == TaskPriority.normal ? {
        normal: null
    } : value == TaskPriority.urgent ? {
        urgent: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n53(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
